Beginner/03. Python/template.py
=> A new print in python!

Beginner/06. Java/matrix-neighbors/Main.java
I'm learning Java and then I did this simple application.
=> A simple java application that prints a matrix value neighbors

README.md
The readme has been updated.Now it gives a brief introduction/idea about what is Hacktober Fest.
=> Updated readme.md Introduction

Beginner/06. Java/Linear search.java, Beginner/06. Java/LinearSearch.java
added linear search program in java folder, beginners
=> added a linear search program in java

Beginner/07. Kotlin/Template.kt
=> Added Kotlin Template 

Beginner/03. Python/MoveZeroes.py
When you work with arrays, the .remove() and .append() methods are precious allies. In this problem I have used them to first remove each zero that belongs to the original array and then append it at the end to the same array.
=> MoveZeroes in python

Projects/fizzbuzz.py
=> fizzbuzz.py

Beginner/04. C++/pointers.cpp
functionality of pointers in cpp
=> pointers.cpp

Beginner/03. Python/fallingdown.py
This is the first project when I tried to create a game in python.
=> create 'falling down' python program

Beginner/04. C++/disjoint_set.cpp
added disjoint set data structure
=> Disjoint set Data Structure in c++

Beginner/04. C++/Graphs.cpp
Graphs Algorithms include:
BFS
DFS
Topological Sort
Shortest Path
Dijkstra
=> added Graphs algorithms

Beginner/06. Java/Recursion/Knapsack.java, Beginner/06. Java/TowerOfHanoi.java
Added Tower Of Hanoi, as well as KnapSack 0-1 problem using Recursion in Java.
Issue relted to it #20 .
=> Add tower of honoi and KnapSack 0-1 in java

Beginner/04. C++/fibbonacci.cpp, Beginner/04. C++/harshal.cpp, Beginner/04. C++/palindrome.cpp
added 3 basic c++ programs into bigginers c++ directory
=> added small c++ programs for bigginers

Projects/Live Sketcher/Live_Sketch_Using_Webcam.ipynb, Projects/Live Sketcher/Readme.md
=> Add live sketcher

Beginner/06. Java/dijkstra/algorithm/Dijkstra.java, Beginner/06. Java/dijkstra/algorithm/DijkstraWithPriorityQueue.java, Beginner/06. Java/dijkstra/algorithm/DijkstraWithoutPriorityQueue.java, Beginner/06. Java/dijkstra/graph/Edge.java, Beginner/06. Java/dijkstra/graph/Graph.java, Beginner/06. Java/dijkstra/graph/Node.java
Hi,
I've implemented the dijkstra algorithm in java.
=> Add Dijkstra Algorithm

Projects/live-html-editor/index.html, Projects/live-html-editor/script.js, Projects/live-html-editor/style.css
Address:- #78 
create live HTML editor in HTML, css and JS
=> add live html editor

Projects/spell_checker/README.md, Projects/spell_checker/spell_checker.py
It is a python script that checks whether the sentence which you have to input has any grammatical error or not.
=> Created spell_checker.py in spell_checker folder

Win coders logo
[readme.txt](https://github.com/wir-coders/Hacktoberfest/files/5310228/readme.txt)
=> Wir Coders logo

Projects/Booklist_app/README.md, Projects/Booklist_app/app.js, Projects/Booklist_app/index.html
Added a simple booklist app using HTML and JS.
=> added a new project

Beginner/04. C++/sum of two numbers.cpp
Added a basic program of adding two number in cpp folder
=> Create sum of two numbers.cpp

Beginner/06. Java/Calculator.java
Simple Java calculator available of doing basic operations such as Addition, Subtraction, Multiplication and Division.
=> Added Simple Calculator In Java For Beginner

Beginner/02. HTML/fibonacci-series.html
=> Fibonacci-series

Beginner/07. Golang/search.go
=> add search on golang

Projects/gold_price/fetch_price.py, Projects/gold_price/test_fetch_price.py
Would highly appreciate feed back on the test cases and if the ways can be improved. 
Thanks, 
Sourab S
=> Test Case for fetch_price.py & Minor Change

Beginner/04. C++/clock-angle.cpp
=> My first pull

Beginner/03. Python/mergesort.py
=> add python code mergesort

Beginner/06. Java/ReverseDigits.java, Beginner/07. C/dda.c
A C program which implements the DDA Line Algorithm for a given set of inputs.
=> Added dda.c

Beginner/03. Python/Palindrome.py
Check whether entered string is palindrome or not.
=> create new Palindrome.py

ATM_Machine.py
I have created a ATM management system which consists of Login , Create new account and exit and also the data is stored in the Accounts.txt file....#hacktoberfest#Hacktoberfest2020
=> ATM management system

Projects/Omi_Bank/app.py
Added My Project in Project's Folder as you said, Omi Banking System...
=> Added my Banking System Project

Projects/ATM machine.py
I have added my awesome ATM management system ..Have a try!!
=> My first ATM Machine

Beginner/08. C/SJF Scheduling Algorithm
I have added the shortest job first scheduling algorithm in C. Please merge my pull request.
=> SJF Scheduling Algorithm

Projects/timecountdown.py
main thing about it is that it will rewrite itself rather than adding more  in terminal.
=> This is a count down script

Beginner/Kotlin/MyRobot/Robot.kt, Beginner/Kotlin/MyRobot/callRobot.kt
I have made a program in Kotlin. A program to see the conversation between a Robot and Human.
There are 2 files ->
Robot.kt :- Contains all properties and behaviours of a robot.
callRobot.kt :- User can  call the robot and ask for some work by executing this file.
Here is a glimpse of the output 
Thank You !
@God-father1
=> A program in Kotlin

Beginner/02. HTML/darklighttheme.html, Beginner/03. Python/helloWorld.py
My first contribution for hacktober fest
=> Added darklighttheme html file

Beginner/04. C++/bubbleSort_OOP.cpp, Beginner/04. C++/heapSort_OOP.cpp, Beginner/04. C++/selectionSort_OOP.cpp
Making this pull request with reference to issue #189
=> Adding sorting algorithms using OOP in C++

Beginner/06. Java/Trees/LeastCommonAncestor
I have added a new folder Tree in java folder and added the code for Least common ancestor of a tree.
=> Added Least Common Ancestor

Beginner/04. C++/coin_change.cpp
Dynamic programming coin change problem in C++
=> DP coin change problem

Beginner/03. Python/joke_machine.py
Added Joke_Machine to the Begginer/03 Python directory
=> Added joke_machine to begginer python

Projects/Metaballs animation/index.html, Projects/Metaballs animation/script.js, Projects/Metaballs animation/style.css
Metaballs animation added to 'Projects' directory
=> Metaballs animation added

Beginner/05. Javascript/Javascript programs/fibonacci.js
Added the javascript program for beginners
=> Added fibonacci javascript program

Beginner/03. Python/Even_or_Odd.py
=> Added even_odd.py

Beginner/08. C/linked_list.c
Added Linked list  under the C folder.
=> Linked List in C

Beginner/04. C++/even odd.cpp, Beginner/04. C++/prime number.cpp
=> to check number is even or odd

Beginner/03. Python/snake.py
please merge it with hacktoberfest label my earlier contributions got neglected because of this. Thanks in advance. Have a great day!
=> added snake game in python.

Beginner/03. Python/remove_duplicates.py
This program features a fairly straight-forward method that removes duplicate numbers from a 2D integer array.
=> Added remove_duplicates.py

Beginner/03. Python/prime_check.py
Algorithm to determine whether a number is a prime number
=> added prime number checker program

Projects/gsap-loader/gsap-loader.html
added html, css and js code for a gsap loading animation
=> add gsap loader

Beginner/03. Python/Duplicate_letter_checker.py
Added Duplicate_letter_checker.py to Beginner\03. Python
=> added Duplicate_letter_checker.py

Beginner/02. HTML/navbar/index.html, Beginner/02. HTML/navbar/style.css
Very attractive change in background color, use of padding, margins and marquee. Have a good knowledge of classes. Set the links to target in new tab.
=> UI design change in nav bar and body

Beginner/03. Python/ZodiacSignTraits.py
A program that displays the zodiac traits according to user input
=> added ZodiacSignTraits program

Projects/InvisibleCloak/colorpicker.py, Projects/InvisibleCloak/core.py
Added a script which lets the user use any colored object as an invisible cloak.
=> Added invisible Cloak

Beginner/04. C++/duplicate_braces.c++
added duplicate_braces.c++ with a problem statement in brief along with my solution to it.
#hacktoberfest
=> added duplicate_braces.c++.

Beginner/03. Python/ZodiacSignTraits.py
=> updated ZodiacSignTraits program 

Projects/asyncio_image_downloader/image_downloader.py, Projects/asyncio_image_downloader/readme.md
This project use asyncio to download images from a website
=> created a project based on asyncio in python

Beginner/03. Python/Dijkistra.py
=> Add Dijikistra to Python

Beginner/03. Python/fizzBuzzLogicRecursion.py
Well commented code to understand each step.
=> Added FizzBuzz Logic using Recursion

Beginner/07. C/Infix to Postfix using Stack.c
=> It will add Infix to Postfix in C language.

Beginner/04. C++/N_Queens.cpp
This is the solution for a very famous backtracking problem N- Queens.
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other.
=> Add Solution for N-Queens Problem

Beginner/04. C++/finding-kthsmallest-array-element-without-actual-sorting.cpp
A cpp algorithm contributed during Hacktoberfest 2020   #47 
Algorithm to find k-th smallest array-element in linear time without actual sorting (Array size: n and 1 <= k <= n)
(i.e. k=1 gives the smallest element of the array and k=n gives the largest)
**Time Complexity: O(n)**
Language: C++
Sample input-output is demonstrated by following screen-shot:
=> Added cpp-algorithm to find kth smallest array element in linear time without actual array sorting

Beginner/03. Python/DoubleIndex.py, Beginner/03. Python/FactorialWithLambda.py, Beginner/03. Python/InvertBinaryTree.py, Beginner/03. Python/LensSlice.py, Beginner/03. Python/MoreFrequentItem.py, Beginner/03. Python/PhysicsClass.py, Beginner/03. Python/SalsShipping.py, Beginner/03. Python/SquaresSorted.py
Have added some solutions to LeetCode and Codecademy problems/tasks in Python.
=> Added Some LeetCode and Codecademy Solutions to Python Folder

Beginner/06. Java/SlidingWindow.java
Using arrays, deque  and linkedlist
=> SlidingWindow in Java

Beginner/08. C/selectionSort.c
Created a script for selection sorting
=> New selection sort technique

Projects/Machine_Learning-Regression/Position_Salaries.csv, Projects/Machine_Learning-Regression/polynomial_regression.py, Projects/Machine_Learning-Regression/random_forest_regression.py
Basic Machine Learning project which involves regression algorithms.
=> Regression Algorithms

Beginner/03. Python/CheckLeapYear.py
this is python program to check whether the year is leap or not , simply pass value of year in 'year' variable , and run the program to get whether it is leap or not
you can also take user input by juts removing some comments in code
=> Python program to Check Leap Year

Beginner/07. C/swap two values.
by this code, we can swap two values using the third variable.
=> Create swap two values.

Beginner/02. HTML/Penguin/Penguin.html
It is a Simple Penguin Webpage.
=> Added Penguin Webpage

Beginner/06. Java/MovieRecommender.java
Added file into respective repo
=> Re-added MovieRecommender.java

Beginner/03. Python/asterisk_diamond.py, Beginner/03. Python/today_is_day.py
=> Program to check the day for the entered date

pysquash.py
I have written a squash game using pygame module. The code is constructed using oops concepts. The code is well commented and easy to understand.
hope you like it. cheers!
=> Added a sqaush game written using python

Beginner/03. Python/HeatIndexCalculator.py
Simple calculator to get the real feel temperature
=> Adding heat index calculator

Beginner/03. Python/caesarEncryption.py
Added Caesar encryption solution along with problem statement in python.
=> Caesar Encryption

Beginner/06. Java/toy_shop.java
Toy shop program in which when toy is bought the toys to the right slides  left to fill the gap of the toy which is bought
New pull request - Array Sliding Implementation
=> java array toy shop implementation

Beginner/03. Python/asterisk_diamond.py, Beginner/03. Python/python_welcomes_you.py, Beginner/03. Python/today_is_day.py
=> Welcome Branch - Prgram for Python welcomes you 

Beginner/03. Python/area_perimeter_of_circle.py, Beginner/03. Python/asterisk_diamond.py, Beginner/03. Python/today_is_day.py
=> Circle Branch - Program to calc area, perimeter of circle

Beginner/03. Python/anagram.py, Beginner/03. Python/asterisk_diamond.py, Beginner/03. Python/today_is_day.py
=> Anagram Branch - Program to check if strings are anagram

Beginner/03. Python/tim_sort.py
new pull request tim sort program in python
=> tim sort program

Beginner/03. Python/queue.py
new pull request for simple implementation of queue (FIFO) using python
=> simple implementation of queue using python

Beginner/03. Python/armstrong.py
153 = 1*1*1 + 5*5*5 + 3*3*3
153 is an Armstrong number.
=> Armstrong Branch - program to cehck if entered number is a armstrong number

12. Dart/binarySearch.dart, 12. Dart/heloWorld.dart
Added a new language to your amazing repository
Added a beginner friendly and intermediate  programs in dart.
=> Added new language - Dart
